services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: frontend
    ports:
      - "3000:3000"
    depends_on:
      - main-server
    restart: unless-stopped

  main-server:
    container_name: main-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: main-server
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/ekz_db
      - MONGODB_URL=mongodb://admin:admin@mongodb:27017
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672

  scraper-worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: scraper-worker
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/ekz_db
      - MONGODB_URL=mongodb://admin:admin@mongodb:27017
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672

  summary-worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: summary-worker
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/ekz_db
      - MONGODB_URL=mongodb://admin:admin@mongodb:27017
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672

  mongodb:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ekz_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  mongodb-data:
  postgres-data:
  rabbitmq-data: