services:
  dev-container:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev-container
    command: sleep infinity
    volumes:
      - ./:/EKZ

#   mongodb:
#     container_name: mongo
#     image: mongodb/mongodb-community-server:latest
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb-data:/data/db
#     environment:
#       MONGODB_INITDB_ROOT_USERNAME: admin
#       MONGODB_INITDB_ROOT_PASSWORD: admin

#   postgres:
#     container_name: postgres
#     image: postgres:latest
#     restart: always
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=takween_db
#       - POSTGRES_USER=admin
#       - POSTGRES_PASSWORD=admin
#       - PGHOST=localhost
#       - PGPORT=5432

#   minio:
#     container_name: minio
#     image: minio/minio
#     restart: always
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     volumes:
#       - minio-data:/data
#     environment:
#       - MINIO_ROOT_USER=admin
#       - MINIO_ROOT_PASSWORD=admin_password
#     command: server /data --console-address ":9001"

# volumes:
#   mongodb-data:
#   postgres-data:
#   minio-data:
