services:
  dev-container:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev-container
    command: sleep infinity
    volumes:
      - ./:/EKZ

  mongodb:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ekz_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGHOST=localhost
      - PGPORT=5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabitmq-data:/var/lib/rabbitmq

    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  mongodb-data:
  postgres-data:
  rabitmq-data: